### ISSUE TITLE
Sodium Extra

### ISSUE THREAD

**Issue by LimeShulkerBox** [Pepperoni-Jabroni/ThirdPersonMaps#1]
This mod shows the map over sodium extra's FPS counter, could you fix this?

![image](https://user-images.githubusercontent.com/77601849/109909845-ecb6c000-7cfa-11eb-8e61-bee268b4474b.png)

**Comment by Pepperoni-Jabroni** [comment]
To fix this, I'll just make the mini-maps entire location configurable. Thanks for reporting!

**Comment by LimeShulkerBox** [comment]
When do you think you will make this? Just curious! Thanks.

**Comment by LimeShulkerBox** [comment]
Just gonna remind you of this!
